/**
 * notificationService.js
 * Create, fetch, and manage user notifications.
 * Notifications are generated by backend triggers or client-side service calls.
 */

import {
  collection,
  doc,
  addDoc,
  getDocs,
  updateDoc,
  deleteDoc,
  query,
  where,
  orderBy,
  onSnapshot,
  serverTimestamp,
  writeBatch,
} from "firebase/firestore";
import { db } from "../firebase";

/**
 * Create a notification for a user.
 * @param {object} data – { recipientId, type, message, taskId?, groupId? }
 */
export async function createNotification(data) {
  await addDoc(collection(db, "notifications"), {
    recipientId: data.recipientId,
    type:        data.type,
    message:     data.message,
    taskId:      data.taskId  ?? null,
    groupId:     data.groupId ?? null,
    read:        false,
    createdAt:   serverTimestamp(),
  });
}

/**
 * Helper: notify multiple users at once (e.g. all task assignees).
 * @param {string[]} uids
 * @param {object}   notifData – { type, message, taskId?, groupId? }
 */
export async function notifyUsers(uids, notifData) {
  await Promise.all(
    uids.map(uid => createNotification({ ...notifData, recipientId: uid }))
  );
}

/**
 * Real-time listener for a user's notifications (unread first).
 * @param {string} uid
 * @param {function} callback
 * @returns {function} unsubscribe
 */
export function subscribeNotifications(uid, callback) {
  const q = query(
    collection(db, "notifications"),
    where("recipientId", "==", uid),
    orderBy("createdAt", "desc")
  );
  return onSnapshot(q, snap => {
    callback(snap.docs.map(d => ({ id: d.id, ...d.data() })));
  });
}

/**
 * Mark a single notification as read.
 * @param {string} notificationId
 */
export async function markAsRead(notificationId) {
  await updateDoc(doc(db, "notifications", notificationId), { read: true });
}

/**
 * Mark all unread notifications for a user as read.
 * @param {string} uid
 */
export async function markAllAsRead(uid) {
  const q    = query(collection(db, "notifications"), where("recipientId", "==", uid), where("read", "==", false));
  const snap = await getDocs(q);
  const batch = writeBatch(db);
  snap.docs.forEach(d => batch.update(d.ref, { read: true }));
  await batch.commit();
}

/**
 * Delete a notification.
 * @param {string} notificationId
 */
export async function deleteNotification(notificationId) {
  await deleteDoc(doc(db, "notifications", notificationId));
}

// ─── Convenience notification creators ───────────────────────────────────────

export async function notifyDeadlineApproaching(uids, taskId, taskTitle, groupId) {
  await notifyUsers(uids, {
    type:    "deadline_approaching",
    message: `Deadline approaching for task: "${taskTitle}"`,
    taskId,
    groupId,
  });
}

export async function notifyTaskOverdue(uids, taskId, taskTitle, groupId) {
  await notifyUsers(uids, {
    type:    "task_overdue",
    message: `Task overdue: "${taskTitle}"`,
    taskId,
    groupId,
  });
}

export async function notifyTaskUpdated(uids, taskId, taskTitle, groupId) {
  await notifyUsers(uids, {
    type:    "task_updated",
    message: `Task was updated: "${taskTitle}"`,
    taskId,
    groupId,
  });
}

export async function notifyMessageReceived(uids, taskId, taskTitle, senderName, groupId) {
  await notifyUsers(uids, {
    type:    "message_received",
    message: `${senderName} sent a message on task: "${taskTitle}"`,
    taskId,
    groupId,
  });
}
